[technote]
id = "DMTN-313"
series_id = "DMTN"
canonical_url = "https://dmtn-313.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-313"
github_default_branch = "main"
date_created = 2025-04-13T03:46:05Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Yusra"
name.family = "AlSayyad"
internal_id = "alsayyady"
orcid = "https://orcid.org/0009-0008-9216-7516"
[[technote.authors.affiliations]]
name = "Department of Astrophysical Sciences"
internal_id = "Princeton-Astro"
address = "Princeton University, Princeton, NJ 08544, USA"
